# Generated by Django 5.1.7 on 2025-03-27 15:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='academic_info', serialize=False, to='bkend.registration')),
                ('high_school_level', models.CharField(blank=True, choices=[('GRADE_10', 'High School Grade 10'), ('O_LEVEL', 'O Level')], max_length=50, null=True)),
                ('high_school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('high_school_address', models.TextField(blank=True, null=True)),
                ('high_school_country', models.CharField(blank=True, max_length=100, null=True)),
                ('english_score', models.CharField(blank=True, max_length=50, null=True)),
                ('math_score', models.CharField(blank=True, max_length=50, null=True)),
                ('highest_qualification', models.CharField(blank=True, choices=[('MATRICULATION', 'Matriculation'), ('GRADE_12', 'High School Grade 12'), ('A_LEVEL', 'A-Level'), ('DIPLOMA', 'Diploma'), ('STAM', 'Sijil Tinggi Agama Malaysia (STAM)'), ('STPM', 'Sijil Tinggi Persekolahan Malaysia (STPM)')], max_length=50, null=True)),
                ('program_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cgpa_score', models.FloatField(blank=True, help_text='Original CGPA/Score from your institution', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cgpa_scale', models.FloatField(blank=True, help_text='Maximum possible CGPA/Score (e.g., 4.0, 5.0, 10.0)', null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('malaysian_equivalent', models.FloatField(blank=True, db_index=True, help_text='Automatically calculated Malaysian equivalent CGPA (scale 4.0)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4.0)])),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('national_language', models.CharField(blank=True, choices=[('ENGLISH', 'English'), ('NON_ENGLISH', 'Non-English')], max_length=50, null=True)),
                ('english_test_type', models.CharField(blank=True, choices=[('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('LINGUASKILL', 'Linguaskill'), ('MUET', 'MUET'), ('OTHER', 'Others')], max_length=50, null=True)),
                ('test_year', models.CharField(blank=True, max_length=4, null=True)),
                ('band_score', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Information',
                'verbose_name_plural': 'Academic Information Records',
                'ordering': ['-malaysian_equivalent'],
                'indexes': [models.Index(fields=['malaysian_equivalent'], name='bkend_acade_malaysi_7f2e53_idx'), models.Index(fields=['highest_qualification'], name='bkend_acade_highest_fc6ff3_idx')],
            },
        ),
    ]
