# Generated by Django 5.1.7 on 2025-03-27 16:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkend', '0002_academicinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='financial_info', serialize=False, to='bkend.registration')),
                ('scholarship_type', models.CharField(blank=True, choices=[('FULL', 'Full Scholarship'), ('PARTIAL_TUITION', 'Partial Scholarship - Tuition Fee Only'), ('PARTIAL_TUITION_ACCOMMODATION', 'Partial Scholarship - Tuition Fee and Accommodation'), ('PARTIAL_TUITION_ALLOWANCE', 'Partial Scholarship - Tuition Fee and Monthly Allowance')], max_length=50, null=True)),
                ('referred_by_organization', models.BooleanField(default=False)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('why_sponsor_essay', models.TextField(blank=True, null=True)),
                ('future_impact_essay', models.TextField(blank=True, null=True)),
                ('suitable_candidate_essay', models.TextField(blank=True, null=True)),
                ('parent1_marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('parent1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent1_identity_number', models.CharField(blank=True, max_length=50, null=True)),
                ('parent1_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('parent1_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('parent1_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('parent1_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('parent1_salary_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('parent2_marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('parent2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent2_identity_number', models.CharField(blank=True, max_length=50, null=True)),
                ('parent2_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('parent2_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('parent2_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('parent2_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('parent2_salary_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('referee1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('referee1_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('referee1_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('referee1_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('referee1_address', models.TextField(blank=True, null=True)),
                ('referee2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('referee2_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('referee2_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('referee2_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('referee2_address', models.TextField(blank=True, null=True)),
                ('has_relative_sponsored', models.BooleanField(default=False)),
                ('relative_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Information',
                'verbose_name_plural': 'Financial Information Records',
            },
        ),
    ]
