# Generated by Django 5.1.7 on 2025-03-27 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkend', '0003_financialinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='documents', serialize=False, to='bkend.registration')),
                ('passport_mykad', models.FileField(blank=True, null=True, upload_to='documents/passport_mykad/', verbose_name='Passport/MYKAD')),
                ('high_school_certificate', models.FileField(blank=True, null=True, upload_to='documents/high_school/', verbose_name='High School Certificate')),
                ('high_school_transcript', models.FileField(blank=True, null=True, upload_to='documents/high_school/', verbose_name='High School Transcript')),
                ('highest_certificate', models.FileField(blank=True, null=True, upload_to='documents/highest_education/', verbose_name='Highest Academic Certificate')),
                ('highest_transcript', models.FileField(blank=True, null=True, upload_to='documents/highest_education/', verbose_name='Highest Academic Transcript')),
                ('english_proficiency', models.FileField(blank=True, null=True, upload_to='documents/english_proficiency/', verbose_name='English Proficiency')),
                ('scholarship_letter', models.FileField(blank=True, null=True, upload_to='documents/scholarship/', verbose_name='Scholarship Letter')),
                ('father_passport', models.FileField(blank=True, null=True, upload_to='documents/parent_docs/', verbose_name="Father's Passport/Death Certificate")),
                ('mother_passport', models.FileField(blank=True, null=True, upload_to='documents/parent_docs/', verbose_name="Mother's Passport/Death Certificate")),
                ('father_income', models.FileField(blank=True, null=True, upload_to='documents/income/', verbose_name="Father's Income Slip")),
                ('mother_income', models.FileField(blank=True, null=True, upload_to='documents/income/', verbose_name="Mother's Income Slip")),
                ('utility_bill', models.FileField(blank=True, null=True, upload_to='documents/utility/', verbose_name='Utility Bill')),
                ('referee_verification', models.FileField(blank=True, null=True, upload_to='documents/referee/', verbose_name='Referee Verification Letter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Upload',
                'verbose_name_plural': 'Document Uploads',
            },
        ),
    ]
