# Generated by Django 5.1.7 on 2025-03-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkend', '0004_documentupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='application_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
