# Generated by Django 5.1.7 on 2025-03-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkend', '0005_registration_application_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
