# Generated by Django 5.1.7 on 2025-04-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkend', '0006_registration_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='country_code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
