# Generated by Django 5.1.7 on 2025-04-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkend', '0007_registration_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='application_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SHORTLISTED', 'Shortlisted for Interview'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='rejected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='shortlisted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='status_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
