# Generated by Django 5.1.7 on 2025-04-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkend', '0008_registration_accepted_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('malaysia', 'Malaysia'), ('west_africa', 'West Africa')], max_length=50)),
                ('original_grade', models.CharField(max_length=10)),
                ('equivalent_weight', models.FloatField()),
            ],
        ),
    ]
