# Generated by Django 5.1.7 on 2025-04-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkend', '0010_prescreeningcriteria_delete_grademapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='prescreeningcriteria',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prescreening Criteria', 'verbose_name_plural': 'Prescreening Criteria'},
        ),
        migrations.RemoveField(
            model_name='prescreeningcriteria',
            name='country',
        ),
        migrations.AlterField(
            model_name='prescreeningcriteria',
            name='max_age',
            field=models.PositiveIntegerField(default=35, help_text='Maximum age requirement for applicants from these countries'),
        ),
        migrations.AlterField(
            model_name='prescreeningcriteria',
            name='min_age',
            field=models.PositiveIntegerField(default=17, help_text='Minimum age requirement for applicants from these countries'),
        ),
        migrations.AddField(
            model_name='prescreeningcriteria',
            name='countries',
            field=models.ManyToManyField(help_text='Select the countries this criteria applies to', related_name='prescreening_criteria', to='bkend.country'),
        ),
    ]
