# Generated by Django 5.1.7 on 2025-04-27 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkend', '0013_delete_prescreeningcriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the country', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='PrescreeningCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the prescreening criteria', max_length=255, unique=True)),
                ('minimum_cgpa', models.FloatField(blank=True, help_text='Minimum CGPA required (scale 4.0)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4.0)])),
                ('minimum_age', models.PositiveIntegerField(blank=True, help_text='Minimum age required', null=True)),
                ('marital_status', models.CharField(blank=True, help_text='Required marital status (e.g., Single, Married)', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countries', models.ManyToManyField(blank=True, help_text='Countries to which this prescreening applies', related_name='prescreening_criteria', to='bkend.country')),
                ('ineligible_countries', models.ManyToManyField(blank=True, help_text='Countries that are not eligible at all', related_name='ineligible_prescreening_criteria', to='bkend.country')),
            ],
            options={
                'verbose_name': 'Prescreening Criteria',
                'verbose_name_plural': 'Prescreening Criteria',
            },
        ),
    ]
