# Generated by Django 5.1.7 on 2025-04-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkend', '0014_country_prescreeningcriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescreeningcriteria',
            name='maximum_age',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum age required', null=True),
        ),
    ]
