# Generated by Django 5.1.7 on 2025-04-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkend', '0015_prescreeningcriteria_maximum_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescreeningcriteria',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Required gender (Male or Female)', max_length=10, null=True),
        ),
    ]
