# Generated by Django 5.1.7 on 2025-04-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkend', '0016_prescreeningcriteria_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicinfo',
            options={'ordering': ['-cgpa_score'], 'verbose_name': 'Academic Information', 'verbose_name_plural': 'Academic Information Records'},
        ),
        migrations.RemoveIndex(
            model_name='academicinfo',
            name='bkend_acade_malaysi_7f2e53_idx',
        ),
        migrations.RemoveField(
            model_name='academicinfo',
            name='cgpa_scale',
        ),
        migrations.RemoveField(
            model_name='academicinfo',
            name='malaysian_equivalent',
        ),
    ]
