# Generated by Django 5.1.7 on 2025-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkend', '0017_alter_academicinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='house_front_view',
            field=models.FileField(blank=True, null=True, upload_to='documents/house/', verbose_name='House Front View'),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='kitchen_view',
            field=models.FileField(blank=True, null=True, upload_to='documents/house/', verbose_name='Kitchen View'),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='living_room_view',
            field=models.FileField(blank=True, null=True, upload_to='documents/house/', verbose_name='Living Room View'),
        ),
    ]
